//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakultetAPI.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmeti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predmeti()
        {
            this.StudentiPredmetis = new HashSet<StudentiPredmeti>();
        }
    
        public int PKPredmetId { get; set; }
        public string Naziv { get; set; }
        public int Godina { get; set; }
        public int FKProfesorId { get; set; }
    
        public virtual Profesori Profesori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentiPredmeti> StudentiPredmetis { get; set; }
    }
}
