//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakultetAPI.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentiPredmeti
    {
        public int FKStudentId { get; set; }
        public int FKPredmetId { get; set; }
        public int Ocjena { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int PKStudPredId { get; set; }
    
        public virtual Predmeti Predmeti { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
